name: CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci --legacy-peer-deps

            - name: Run unit tests
              run: npm run test

            - name: Build library
              run: npx ng build ngx-fluent-design --configuration production

            # Leaving for now until I can get Cypress to run in GitHub
            # - name: Cypress run
            #   uses: cypress-io/github-action@v6
            #   with:
            #       start: npm run start
            #       wait-on: 'http://localhost:8080'
